# Generated by Django 5.1.15 on 2026-07-04 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "is_anonymous",
                    models.BooleanField(default=True, verbose_name="익명 신고"),
                ),
                (
                    "reporter_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="신고자 이름"
                    ),
                ),
                (
                    "reporter_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="신고자 연락처"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "접수"),
                            ("REVIEWING", "검토중"),
                            ("DONE", "처리완료"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="접수 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
            ],
            options={
                "verbose_name": "신고",
                "verbose_name_plural": "신고 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("VIEW_IDENTITY", "신원 정보 열람")],
                        default="VIEW_IDENTITY",
                        max_length=30,
                        verbose_name="행위",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="열람 시각"),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="열람 관리자",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="reports.report",
                        verbose_name="대상 신고",
                    ),
                ),
            ],
            options={
                "verbose_name": "신원 열람 로그",
                "verbose_name_plural": "신원 열람 로그",
                "ordering": ["-viewed_at"],
            },
        ),
    ]
