# Generated by Django 5.1.15 on 2026-07-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ["-created_at"],
                "permissions": [("view_identity", "신원 정보(이름·연락처) 열람 가능")],
                "verbose_name": "신고",
                "verbose_name_plural": "신고 목록",
            },
        ),
    ]
